/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace Messaging {
    export interface MessagingService {
        connectSocket(
            data: ConnectSocketReq,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ConnectSocketRes>;
        disConnectSocket(
            data: DisConnectSocketReq,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<DisConnectSocketRes>;
    }
    export interface ConnectSocketReq {
        userId?: number;
    }
    export interface ConnectSocketRes {
        socketId?: number;
        status?: string;
    }
    export interface DisConnectSocketReq {
        socketId?: string;
    }
    export interface DisConnectSocketRes {
        status?: string;
    }
}

